/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardDownloadsRouteImport } from './routes/dashboard/downloads'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardStorageRouteImport } from './routes/dashboard/storage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDownloadsRoute = DashboardDownloadsRouteImport.update({
  id: '/dashboard/downloads',
  path: '/dashboard/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStorageRoute = DashboardStorageRouteImport.update({
  id: '/dashboard/storage',
  path: '/dashboard/storage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard/downloads'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard/downloads'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard/downloads'
    | '/dashboard/settings'
    | '/dashboard/storage'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  DashboardDownloadsRoute: typeof DashboardDownloadsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStorageRoute: typeof DashboardStorageRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/downloads': {
      id: '/dashboard/downloads'
      path: '/dashboard/downloads'
      fullPath: '/dashboard/downloads'
      preLoaderRoute: typeof DashboardDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/storage': {
      id: '/dashboard/storage'
      path: '/dashboard/storage'
      fullPath: '/dashboard/storage'
      preLoaderRoute: typeof DashboardStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  DashboardDownloadsRoute: DashboardDownloadsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStorageRoute: DashboardStorageRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
